@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "OPERATOR" as OP
participant "ListCandidatesUI" as UI
participant "CandidateController" as CTRL
participant "ListCandidatesService" as LISVC
participant "CandidateRepository" as CREPO
participant "Candidate" as APP

OP -> UI: listCandidates()
activate UI
UI -> CTRL: listCandidates()
activate CTRL
CTRL -> LISVC: listCandidates()
activate LISVC
LISVC -> CREPO: listCandidates()
activate CREPO
CREPO -> APP: findAll()
activate APP
APP --> CREPO: List<Candidate>
deactivate APP
CREPO --> LISVC: List<Candidate>
deactivate CREPO
LISVC --> CTRL: List<Candidate>
deactivate LISVC
CTRL --> UI: List<Candidate>
deactivate CTRL
UI --> OP: List<Candidate>
deactivate UI

@enduml
