@startuml

package Presentation {
    class RegisterJobOpeningUI
}

package Domain {
    class JobOpening
    class JobOpeningBuilder
}

package Persistence {
    class JpaJobOpeningRepository
    interface JobOpeningRepository
}

package Application {
    class RegisterJobOpeningController
}



Presentation.RegisterJobOpeningUI --> Application.RegisterJobOpeningController
Application.RegisterJobOpeningController --> Persistence.JobOpeningRepository
Application.RegisterJobOpeningController --> Domain.JobOpeningBuilder
Domain.JobOpeningBuilder --> Domain.JobOpening
Persistence.JobOpeningRepository <|-- Persistence.JpaJobOpeningRepository

@enduml