@startuml

package Presentation {
    class RegisterJobOpeningUI
}

package Domain {
    class JobOpening
}

package Persistence {
    class JpaJobOpeningRepository
}

package Application {
    class JobOpeningController
}



Presentation.RegisterJobOpeningUI --> Application.JobOpeningController
Application.JobOpeningController --> Persistence.JpaJobOpeningRepository
Application.JobOpeningController --> Domain.JobOpening

@enduml