@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "CustomerManager" as CM
participant "RegisterJobOpeningUI" as UI
participant "RegisterJobOpeningController" as CTRL
participant "JobOpening" as JO
participant "JobOpeningRepository" as JOREPO



activate CM
    CM -> UI : registerJobOpening()
    activate UI
        UI -> CTRL : registerJobOpening()
        activate CTRL
            CTRL -> JO : new JobOpening()
            activate JO
                JO --> CTRL : return JobOpening
            deactivate JO
            CTRL -> JOREPO : save(JobOpening)
        deactivate CTRL
        UI --> CM : inform if job opening was registered or not
    deactivate UI
deactivate CM




@enduml